[versions]
java = "24"
communidirect = "1.1.0"
lanterna = "3.1.2"

[libraries]
lanterna = { group = "com.googlecode.lanterna", name = "lanterna", version.ref = "lanterna" }

[plugins]
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version = "0.8.0" }